included:

excluded:
  - "**/*.generated.swift"
  - Pods

disabled_rules:
  - line_length
  - trailing_whitespace
  - trailing_comma
  - cyclomatic_complexity
  - function_body_length

custom_rules:
  lottie_animation_initialization:
    included: ".*\\.swift"
    name: "Lottie animation initialization"
    regex: '(LottieAnimationView\(name:|LottieAnimation\.named\()\s*".*?"\s*\)'
    message: "Use R.file.filename.name or typealias of this instead."
    severity: error
    match_kinds:
      - identifier
      - string

  image_name_initialization:
    included: ".*\\.swift"
    name: "Image initialization"
    regex: '(UIImage\(named:\s*".*?"\s*\)|Image\(\s*".*?"\s*\))'
    message: "Use R.image.name() or typealias of this instead."
    severity: error
    match_kinds:
      - identifier
      - string

  disallow_string_registering:
    included: ".*\\.swift"
    name: "Avoid String Literals for Registering Cells/Views"
    regex: 'register\s*\(.*?(forCellReuseIdentifier|forCellWithReuseIdentifier|forHeaderFooterViewReuseIdentifier|withReuseIdentifier)\:\s*\".*?\"'
    message: "Avoid using string literals when registering cells or views in UITableView/UICollectionView. Use constants or identifiers instead."
    severity: error

  disallow_string_dequeueing:
    included: ".*\\.swift"
    name: "Avoid String Literals for Dequeueing Cells/Views"
    regex: '(dequeueReusableCell|dequeueReusableHeaderFooterView)\s*\(\s*(withIdentifier|withReuseIdentifier):\s*\".*?\"'
    message: "Avoid using string literals when dequeueing cells or views in UITableView/UICollectionView. Use constants or identifiers instead."
    severity: error

  disallow_string_supplementary_dequeueing:
    included: ".*\\.swift"
    name: "Avoid String Literals for Dequeueing Supplementary Views"
    regex: 'dequeueReusableSupplementaryView\(ofKind: .*?,\s*withReuseIdentifier:\s*\".*?\"'
    message: "Avoid using string literals when dequeueing supplementary views in UICollectionView. Use constants or identifiers instead."
    severity: error

  sf_safe_symbol:
    included: ".*\\.swift"
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: '(Image\(systemName:)|(NSImage\(symbolName:)|(Label[^,]+?,\s*systemImage:)|(UIApplicationShortcutIcon\(systemImageName:)'
    severity: error
    match_kinds:
      - identifier
      - string

  force_flags:
    included: ".*\\.swift"
    name: "Debug flags"
    regex: 'let\s+force(?:Premium|OfflinePaywall|OfflineSlides)\s*=\s*true'
    message: "Force flags must be disabled after testing."
    severity: warning
    match_kinds:
      - identifier
      - keyword

  cancle_misspelling:
    included: ".*\\.swift"
    name: "Misspelled 'cancle'"
    regex: '(?i)\bcancle\b'
    message: "Did you mean 'cancel'?"
    severity: warning
    match_kinds:
      - identifier
      - string

  acces_misspelling:
    included: ".*\\.swift"
    name: "Misspelled 'acces'"
    regex: '(?i)\bacces\b'
    message: "Did you mean 'access'?"
    severity: warning
    match_kinds:
      - identifier
      - string

identifier_name:
  min_length:
    warning: 2