included:

excluded:
  - "**/*.generated.swift"
  - "*.generated.swift"
  - Pods

disabled_rules:
  - line_length
  - trailing_whitespace
  - trailing_comma
  - cyclomatic_complexity
  - function_body_length
  - type_body_length

custom_rules:
  lottie_animation_initialization:
    name: "[LA] Lottie animation initialization"
    regex: '(LottieAnimationView\(name:|LottieAnimation\.named\()\s*".*?"\s*\)'
    message: "Use R.file.filename.name or typealias of this instead."
    severity: error

  image_name_initialization:
    name: "[LA] Image initialization"
    regex: '(UIImage\(named:\s*".*?"\s*\)|Image\(\s*".*?"\s*\))'
    message: "Use R.image.name() or typealias of this instead."
    severity: error

  disallow_string_registering:
    name: "[LA] Avoid String Literals for Registering Cells/Views"
    regex: 'register\s*\(.*?(forCellReuseIdentifier|forCellWithReuseIdentifier|forHeaderFooterViewReuseIdentifier|withReuseIdentifier)\:\s*\".*?\"'
    message: "Avoid using string literals when registering cells or views in UITableView/UICollectionView. Use constants or identifiers instead."
    severity: error

  disallow_string_dequeueing:
    name: "[LA] Avoid String Literals for Dequeueing Cells/Views"
    regex: '(dequeueReusableCell|dequeueReusableHeaderFooterView)\s*\(\s*(withIdentifier|withReuseIdentifier):\s*\".*?\"'
    message: "Avoid using string literals when dequeueing cells or views in UITableView/UICollectionView. Use constants or identifiers instead."
    severity: error

  disallow_string_supplementary_dequeueing:
    name: "[LA] Avoid String Literals for Dequeueing Supplementary Views"
    regex: 'dequeueReusableSupplementaryView\(ofKind: .*?,\s*withReuseIdentifier:\s*\".*?\"'
    message: "Avoid using string literals when dequeueing supplementary views in UICollectionView. Use constants or identifiers instead."
    severity: error

  sf_safe_symbol:
    name: "[LA] Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: '(Image\(systemName:)|(NSImage\(symbolName:)|(Label[^,]+?,\s*systemImage:)|(UIApplicationShortcutIcon\(systemImageName:)'
    severity: error

  nsfetchrequest_rule:
    name: "[LA] NSFetchRequest Usage Rule"
    message: "Avoid hardcoding entity names in NSFetchRequest."
    regex: 'NSFetchRequest<.*?>\(\s*entityName:\s*".*?"\)'
    severity: warning

  nsentitydescription_rule:
    name: "[LA] NSEntityDescription Usage Rule"
    message: "Avoid hardcoding entity names in NSEntityDescription."
    regex: 'NSEntityDescription\.entity\(\s*forEntityName:\s*".*?",'
    severity: warning

  nssortdescriptor_rule:
    name: "[LA] NSEntityDescription Usage Rule"
    message: "Avoid hardcoding entity attributes in NSSortDescriptor."
    regex: 'NSSortDescriptor\(\s*key:\s*".*?",'
    severity: warning

  nspredicate_rule:
    name: "[LA] NSPredicate Usage Rule"
    message: "Avoid hardcoding entity attributes in NSPredicate."
    regex: 'NSPredicate\(\s*format:\s*"\s*(?!(SELF|%K))'
    severity: warning

  bundle_resource_rule:
    name: "[LA] Avoid Hardcoded Bundle Access"
    message: "Avoid hardcoding filenames for resource access."
    regex: "Bundle\\.main\\.(url|path)\\(forResource:\\s*\\\".+\\\",\\s*(withExtension|ofType):\\s*\\\".+\\\"\\)"
    severity: warning

  bundle_resource_rule_swiftui:
    included: ".*\\.swift"
    name: "[LA] Avoid Hardcoded Bundle Access"
    message: "Avoid hardcoding filenames for resource access."
    regex: "DotLottieFile\\.named\\(\\s*\\\".+\\\"\\s*\\)"
    severity: warning

  force_flags:
    name: "[LA] Debug flags"
    regex: 'let\s+force(?:Premium|OfflinePaywall|OfflineSlides)\s*=\s*true'
    message: "Force flags must be disabled after testing."
    severity: warning

  test_api:
    name: "[LA] Test API used"
    regex: '\".*?(geofinder|homeworkai)test\.info.*?\"'
    message: "Test API must be replaced with real one after testing."
    severity: warning

  revenuecat_id_assignment:
    name: "[LA] RevenueCat ID Assignment"
    regex: 'UserDefaults\.revenueCatID\s*=\s*(?:(?!AppsFlyerLib\.shared\(\)\.getAppsFlyerUID\(\)).)+$'
    message: "UserDefaults.revenueCatID must be assigned to AppsFlyerLib.shared().getAppsFlyerUID()."
    severity: warning

identifier_name:
  min_length:
    warning: 2