included:

excluded:
  - "_obfuscated"
  - "**/*-Obfuscated.swift"
  - "**/*.generated.swift"

disabled_rules:
  - line_length
  - trailing_whitespace
  - trailing_comma
  - cyclomatic_complexity
  - function_body_length

custom_rules:
  image_name_initialization: # Disable UIImage init from name
    included: ".*.swift"
    name: "Image initialization"
    regex: 'UIImage\(named:[^)]+\)'
    message: "Use R.image.name() or typealias of this instead."
    severity: error
    match_kinds:
      - identifier
      - string

  sf_safe_symbol:
    included: ".*.swift"
    name: "Safe SFSymbol"
    message: "Use `SFSafeSymbols` via `systemSymbol` parameters for type safety."
    regex: "(Image\\(systemName:)|(NSImage\\(symbolName:)|(Label[^,]+?,\\s*systemImage:)|(UIApplicationShortcutIcon\\(systemImageName:)"
    severity: warning
    match_kinds:
      - identifier
      - string
      
  force_flags:
    included: ".*.swift"
    name: "Debug flags"
    regex: "let\\s+force(Premium|OfflinePaywall|OfflineSlides)\\s*=\\s*true"
    message: "Force flags must be disabled after testing."
    severity: warning
    match_kinds:
      - identifier
      - keyword

  cancle_misspelling:
    included: ".*.swift"
    name: "Misspelled 'cancle'"
    regex: '(?i)\bcancle\b'
    message: "Did you mean 'cancel'?"
    severity: warning
    match_kinds:
      - identifier
      - string

  acces_misspelling:
    included: ".*.swift"
    name: "Misspelled 'acces'"
    regex: '(?i)\bacces\b'
    message: "Did you mean 'access'?"
    severity: warning
    match_kinds:
      - identifier
      - string

identifier_name:
  min_length:
    warning: 2
